pimcore:
    workflows:
        workflow:
            label: "Product Workflow"
            type: "state_machine"
            supports:
                - 'Pimcore\Model\DataObject\Electronics'
            places:
                base:
                    label: "Base Attributes"
                    color: "#377ea9"
                    permissions:
                        - objectLayout: 1
                price:
                    label: "price"
                    color: "#28a013"
                    permissions:
                        - objectLayout: 2
                features:
                    label: "features"
                    title: "Updating content step"
                    color: "#d9ef36"
                    permissions:
                        - objectLayout: 5
                development:
                    label: "Update Manufacturer + Seller"
                    title: "Update Manufacturer + Seller"
                    color: "#d9ef36"
                    permissions:
                        - objectLayout: 6
                media:
                    label: "media"
                    title: "Image color gallery"
                    color: "#d9ef36"
                    permissions:
                        - objectLayout: 4
                content_prepared:
                    label: "Content Prepared"
                    title: "Content ready to publish"
                    color: "#28a013"
                accepted:
                    label: "Accepted product"
                    color: "#28a013"

                reject:
                    label: "Reject product"
                    color: "#28a013"

            transitions:
                add_base_attributes:
                    from: base
                    to: price
                    guard: "is_fully_authenticated() and is_granted('ROLE_DATAENTRY')"
                    options:
                        label: "set base attributes"
                        notes:
                            commentEnabled: true
                            commentRequired: true
                add_price:
                    from:  price
                    to: features
                    guard: "is_fully_authenticated() and is_granted('ROLE_DATAENTRY')"
                    options:
                        label: "set price"
                        notes:
                            commentEnabled: true
                            commentRequired: false
                add_features:
                    from: features
                    to: development
                    guard: "is_fully_authenticated() and is_granted('ROLE_DATAENTRY')"
                    options:
                        label: "set features"
                        notes:
                            commentEnabled: true
                            commentRequired: false

                add_mf_sl:
                    from: development
                    to: media
                    guard: "is_fully_authenticated() and is_granted('ROLE_DATAENTRY')"
                    options:
                        label: "set development"
                        notes:
                            commentEnabled: true
                            commentRequired: false
                
                add_media:
                    from: media
                    to: content_prepared
                    guard: "is_fully_authenticated() and is_granted('ROLE_MEDIA')"
                    options:
                        label: "prepare"
                        notes:
                            commentEnabled: true
                            commentRequired: false
                accept_transition:
                    from: content_prepared
                    to: accepted
                    guard: "is_fully_authenticated() and is_granted('ROLE_REVIEWER')"
                    options:
                        label: "accept"
                        notes:
                            commentEnabled: true
                            commentRequired: false

                reject_transition:
                    from: content_prepared
                    to: reject
                    guard: "is_fully_authenticated() and is_granted('ROLE_REVIEWER')"
                    options:
                        label: "reject"
                        notes:
                            commentEnabled: true
                            commentRequired: false

               

               