pimcore:
    custom_report:
        definitions:
            electronics:
                name: electronics
                sql: ''
                dataSourceConfig:
                    -
                        sql: 'category, Count(*)'
                        from: object_electronics
                        where: ''
                        groupby: category
                        type: sql
                columnConfiguration:
                    -
                        name: category
                        display: true
                        export: true
                        order: true
                        width: ''
                        label: ''
                        id: extModel1820-3
                    -
                        name: 'Count(*)'
                        display: true
                        export: true
                        order: true
                        width: ''
                        label: ''
                        id: extModel1820-4
                niceName: ''
                group: ''
                groupIconClass: ''
                iconClass: ''
                menuShortcut: true
                reportClass: ''
                chartType: pie
                pieColumn: 'Count(*)'
                pieLabelColumn: category
                xAxis: null
                yAxis: {  }
                modificationDate: 1676456175
                creationDate: 1676018880
                shareGlobally: true
                sharedUserNames:
                    - admin
                sharedRoleNames: {  }
